### ISSUE TITLE
Does repo is functional if built ?

### ISSUE THREAD

**Issue by AKprisonER** [TrustWallet/trust-wallet-android-source#1]
If i generate and use apk using this existing repo, will the apk works good on Main ethereum network ?
Or does it spoils my ethereum?

**Comment by vikmeup** [comment]
It will work! Feel free to check it out!

**Comment by vikmeup** [comment]
Even tho I will suggest to use latest version from Google Play: https://play.google.com/store/apps/details?id=com.wallet.crypto.trustapp

**Comment by maratsubkhankulov** [comment]
Closing as done
