### ISSUE TITLE
Incorrect work of Add token by reading QR 

### ISSUE THREAD

**Issue by jmenhome** [TrustWallet/trust-wallet-android-source#12]
Hello!
I try to export Token info using QR code. App version 1.5.40

When I try to scan code - all content pushes to Address field in interface (ethereum:0xCONTRACTADDRESS?name=PROJECTNAME&symbol=CONTRACTSYMBOL&decimals=18), nothing parsed. I try to show only address in QR, but nothing fetched, simply Address field filled.

I contact developers in IOs thread - they say that I must put only contract address to this QR, next application make RPC call, fetch additional data (symbol, decimals) and put it in dialog. Can you update app functional?

**Comment by vikmeup** [comment]
@jmenhome this is not expected behavior tho. Currently it only parses ethereum address. the rest you have to enter manually, but we gonna be adding functionality to fetch smart contract address info automatically.

Also, tokens just show up automatically, why do you add them manually?

**Comment by jmenhome** [comment]
You write about RPC call for params:
>>Actually all we need is to scan smart contract address. Then do RPC calls to fetch decimals, name and symbol
About Android version - it don't parse QR info, so all string pushes to Address, they must fix it.

I test IOs version - it don't make any request, only parse address. Also I read code, it parse info from qr (symbol, digitals). Why you don't add it to form?

If somebody send tokens to my address token will be added automatically? I don't test ts yet..

**Comment by vikmeup** [comment]
@jmenhome tokens will be added automatically, user won't need to ever bother with that :) so parsing doesn't make much sense atm.

**Comment by jmenhome** [comment]
yes, I test it, automatically add work fine!
But maybe in such great application button must work excellent and equally on all platforms?

**Comment by vikmeup** [comment]
@jmenhome we always looking for people to help us improve both iOS and Android apps! We focused on building featured on iOS and then port them to Android :) 

I will close this issue for now.
