### ISSUE TITLE
Failed to send transaction before previous one confirmed

### ISSUE THREAD

**Issue by emn178** [TrustWallet/trust-wallet-android-source#25]
Android version can't send multiple transactions in short time. It will show transaction error. 
This causes by following code:
https://github.com/TrustWallet/trust-wallet-android-source/blob/7255178af39a219dba9cd009c7225671531560bf/app/src/main/java/com/wallet/crypto/trustapp/repository/TransactionRepository.java#L80-L83

The nonce doesn't increase because previous one is not confirmed. Maybe change to
```
DefaultBlockParameterName.PENDING
```
can fixed it. or manage nonce like ios version
https://github.com/TrustWallet/trust-wallet-ios/blob/4d2c0ead34f84216d017944763b6a53280c4ccab/Trust/EtherClient/Providers/Providers/GetNonceProvider.swift

**Comment by vikmeup** [comment]
@emn178 we currently only have 1 pending transaction in the stack, for UX reasons, unless you specify  nonce value in the app. Otherwise users have too many pending transactions, because they set low gas fee.

**Comment by emn178** [comment]
iOS version uses different UX? It has no this issue.

**Comment by vikmeup** [comment]
@emn178 iOS allows you to have many pending transaction.

Android users tend to be cheaper on gas :( but this will be changed soon. I just want to avoid issues with stuck transactions, too many users complaining then, because ethereum network is slow and expensive.
