### ISSUE TITLE
Token send Txn defaults to 0 eth

### ISSUE THREAD

**Issue by chaparral13** [TrustWallet/trust-wallet-android-source#33]
When trying to send tokens the transaction defaults to 0 ETH sent. Transaction is successful but it's not sending anything. 
Please help or point me in right direction

**Comment by vikmeup** [comment]
@chaparral13 can you wait for couple of hours, new build is sent to the Google Play.

Version 1.6.146 or higher has this fix. 

Thanks

**Comment by chaparral13** [comment]
Thank you sir


Sent from my  U.S.Cellular© Smartphone
-------- Original message --------From: Viktor Radchenko <notifications@github.com> Date: 9/27/18  10:41 PM  (GMT-06:00) To: TrustWallet/trust-wallet-android-source <trust-wallet-android-source@noreply.github.com> Cc: chaparral13 <allan.r.poggiosantos@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [TrustWallet/trust-wallet-android-source] Token send Txn defaults
  to 0 eth (#33) 
@chaparral13 can you wait for couple of hours, new build is sent to the Google Play.
Version 1.6.146 or higher has this fix.
Thanks

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/TrustWallet/trust-wallet-android-source","title":"TrustWallet/trust-wallet-android-source","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/TrustWallet/trust-wallet-android-source"}},"updates":{"snippets":[{"icon":"PERSON","message":"@vikmeup in #33: @chaparral13 can you wait for couple of hours, new build is sent to the Google Play.\r\n\r\nVersion 1.6.146 or higher has this fix. \r\n\r\nThanks"}],"action":{"name":"View Issue","url":"https://github.com/TrustWallet/trust-wallet-android-source/issues/33#issuecomment-425311550"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/TrustWallet/trust-wallet-android-source/issues/33#issuecomment-425311550",
"url": "https://github.com/TrustWallet/trust-wallet-android-source/issues/33#issuecomment-425311550",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [TrustWallet/trust-wallet-android-source] Token send Txn defaults to 0 eth (#33)",
"sections": [
{
"text": "",
"activityTitle": "**Viktor Radchenko**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@vikmeup",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"TrustWallet/trust-wallet-android-source\",\n\"issueId\": 33,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/TrustWallet/trust-wallet-android-source/issues/33#issuecomment-425311550"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 385267810\n}"
}
],
"themeColor": "26292E"
}
]
