### ISSUE TITLE
The app does not ask for authentication unless closed explicitly

### ISSUE THREAD

**Issue by nnkken** [TrustWallet/trust-wallet-android-source#9]
After entering the app with my fingerprint, if I don't press the back button to quit the app, and instead just press the home button, then no matter how much time passed, the app does not ask for fingerprint / pin-code when reopening.

Procedure to reproduce:
1. open the app
2. unlock by fingerprint
3. press home button
4. normally use the phone and sometimes screen off
5. after a few hours, open the app again
6. still no authentication needed

I personally think that this is a big security problem, since I usually don't close an app by pressing the back button multiple times. I expect the app to ask for authentication whenever it is killed, close, suspended, or switched to other apps.

Platform: Xiaomi Mi 5, 3GB RAM, with MIUI 9.2.1.0 (Android 7.0)

**Comment by vikmeup** [comment]
This is inactive repo, please read: https://medium.com/@trustwallet/why-open-sourcing-android-app-could-be-a-harm-to-the-crypto-community-fb3ae1707dc6

**Comment by maratsubkhankulov** [comment]
@nnkken I understand your expectation. We had to make a call between convenience and security. There is no way on android (that we've found) to tell when the app is suspended, so pin the pin/fingerprint on you'd have to ask for it either on a timer or after every time you opened a particular screen, so we chose to ask for it only  on startup. Close the app to lock it.

**Comment by nnkken** [comment]
Isn't there a hook (`onPause`) for suspended app?
https://developer.android.com/guide/components/activities/activity-lifecycle.html
I'm not familiar with Android development, maybe I'm wrong. Anyway thanks for your reply!

**Comment by maratsubkhankulov** [comment]
the `onPause` will be triggered when the activity is paused but not the app as a whole. I'm certain there is a way and one such way is to use Fragments. Once we come around to that we'll revisit adding that kind of protection.
